chore(ci): enhance iOS build workflow with error handling for keychain and code signing

diff --git a/.github/workflows/flutter.yaml b/.github/workflows/flutter.yaml
--- a/.github/workflows/flutter.yaml
+++ b/.github/workflows/flutter.yaml
@@ -100,19 +100,37 @@ jobs:
       - name: Sign iOS App
         if: matrix.platform == 'ios'
         run: |
+          echo "Creating Keychain..."
           security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
           security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
           security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
-          
-          # Import the provisioning profile
-          echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/my_profile.mobileprovision
-          
-          # Import the certificate
-          echo "${{ secrets.IOS_CERTIFICATE }}" | base64 --decode > certificate.p12
-          security import certificate.p12 -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
 
-          # Code signing
-          codesign -f -s "${{ secrets.IOS_CERTIFICATE_NAME }}" --deep --timestamp --options=runtime ${{ env.build_path }}/*.app
+          echo "Importing Provisioning Profile..."
+          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles/
+          echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/my_profile.mobileprovision
+          if [ -f ~/Library/MobileDevice/Provisioning\ Profiles/my_profile.mobileprovision ]; then
+            echo "Provisioning profile imported successfully."
+          else
+            echo "Failed to import provisioning profile."
+            exit 1
+          fi
+
+          echo "Importing Certificate..."
+          echo "${{ secrets.IOS_CERTIFICATE }}" | base64 --decode > certificate.p12
+          if security import certificate.p12 -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign; then
+            echo "Certificate imported successfully."
+          else
+            echo "Failed to import certificate."
+            exit 1
+          fi
+
+          echo "Signing App..."
+          if codesign -f -s "${{ secrets.IOS_CERTIFICATE_NAME }}" --deep --timestamp --options=runtime ${{ env.build_path }}/*.app; then
+            echo "Code signing succeeded."
+          else
+            echo "Code signing failed."
+            exit 1
+          fi
 
       # Upload Artifact
       - name: Upload Artifact
