chore(fix): update Flutter workflow to use timestamp-based versioning and add email notifications for build success and failure

diff --git a/.github/workflows/flutter.yaml b/.github/workflows/flutter.yaml
--- a/.github/workflows/flutter.yaml
+++ b/.github/workflows/flutter.yaml
@@ -63,10 +63,10 @@ jobs:
       - name: Manage Versioning
         id: version
         run: |
-          set -e
+          set -e  # Exit immediately if a command exits with a non-zero status
           CURRENT_VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //;s/+.*//') || { echo "Failed to read version"; exit 1; }
-          NEW_BUILD=$(( $(echo $CURRENT_VERSION | awk -F '+' '{print $2}') + 1 )) || { echo "Failed to calculate new build number"; exit 1; }
-          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F '+' '{print $1}')+"$NEW_BUILD" || { echo "Failed to create new version string"; exit 1; }
+          BUILD_NUMBER=$(date +%Y%m%d%H%M%S)  # Unique build number based on current timestamp
+          NEW_VERSION="${CURRENT_VERSION}+$BUILD_NUMBER" || { echo "Failed to create new version string"; exit 1; }
           echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
           pubspec_version change --version "$NEW_VERSION" || { echo "Failed to update pubspec version"; exit 1; }
 
@@ -103,9 +103,14 @@ jobs:
           security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
           security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
           
+          # Import the provisioning profile
           echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/my_profile.mobileprovision
+          
+          # Import the certificate
           echo "${{ secrets.IOS_CERTIFICATE }}" | base64 --decode > certificate.p12
           security import certificate.p12 -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
+
+          # Code signing
           codesign -f -s "${{ secrets.IOS_CERTIFICATE_NAME }}" --deep --timestamp --options=runtime ${{ env.build_path }}/*.app
 
       # Upload Artifact
@@ -118,7 +123,6 @@ jobs:
 
       # Rilis Aplikasi
       - name: Rilis Aplikasi
-        id: release
         uses: softprops/action-gh-release@v1
         with:
           tag_name: ${{ env.NEW_VERSION }}
@@ -126,22 +130,12 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      # Update tag if exists
-      - name: Check and Create Tag
-        run: |
-          git fetch --tags
-          if git rev-parse "refs/tags/${{ env.NEW_VERSION }}" >/dev/null 2>&1; then
-            echo "Tag ${NEW_VERSION} already exists. Skipping tag creation."
-          else
-            git tag ${{ env.NEW_VERSION }}
-            git push origin ${{ env.NEW_VERSION }}
-          fi
-
   cleanup:
     runs-on: ubuntu-latest
     needs: [build]
     if: always()
     steps:
+      # Kirim notifikasi email jika gagal
       - name: Kirim notifikasi email jika gagal
         if: failure()
         uses: dawidd6/action-send-mail@v3
@@ -157,6 +151,7 @@ jobs:
           username: ${{ secrets.SMTP_USER }}
           password: ${{ secrets.SMTP_PASSWORD }}
 
+      # Kirim notifikasi email jika sukses
       - name: Kirim notifikasi email jika sukses
         if: success() && github.ref == 'refs/heads/main'
         uses: dawidd6/action-send-mail@v3
